name: ROR API CI/CD
on:
  push:
    branches: ["main"]
env:
  REMOTE_DATABASE_URL: ${{ secrets.REMOTE_DATABASE_URL }}
  SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
  RAILS_ENV: production
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          chmod +x set_env.sh
          ./set_env.sh
          docker build -t ror-api .
          docker tag ror-api ${{ secrets.DOCKER_USERNAME }}/ror-api:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/ror-api:${{ github.sha }}

      - name: ssh to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: azureuser
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker stop ror-api
            sudo docker rm ror-api
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/ror-api:${{ github.sha }}
            sudo docker run -d -p 4000:4000 --name ror-api --restart unless-stopped ${{ secrets.DOCKER_USERNAME }}/ror-api:${{ github.sha }}
